#!/bin/bash

unset LD_PRELOAD

export LD_PRELOAD="/opt/vmware/gcc_4.9.2/libglibmm-2.4.so.1.3.0 /opt/vmware/gcc_4.9.2/libgiomm-2.4.so.1.3.0 /opt/vmware/gcc_4.9.2/libpangomm-1.4.so.1.0.30 /opt/vmware/gcc_4.9.2/libgdkmm-2.4.so.1.1.0 /opt/vmware/gcc_4.9.2/libgtkmm-2.4.so.1.1.0 /opt/vmware/gcc_4.9.2/libcairomm-1.0.so.1.4.0"

exec /opt/vmware/bin/vmware $@

exit 0
